### ISSUE TITLE
Doesn't compile on Ubuntu 12.10.

### ISSUE THREAD

**Issue by rpasta42** [irungentoo/toxcore#419]
When trying to compile I get this errors:

`
Scanning dependencies of target toxcore
---------------------blah blah everything's compiling fine-------------------
[ 92%] Built target DHT_bootstrap_daemon
Scanning dependencies of target friends_test
[ 96%] Building C object auto_tests/CMakeFiles/friends_test.dir/friends_test.c.o
Linking C executable friends_test
[ 96%] Built target friends_test
Scanning dependencies of target messenger_test
[100%] Building C object auto_tests/CMakeFiles/messenger_test.dir/messenger_test.c.o
Linking C executable messenger_test
/usr/lib/gcc/x86_64-linux-gnu/4.7/../../../x86_64-linux-gnu/libcheck.a(check.o): In function`tcase_create':
(.text+0x18c): undefined reference to `floor'
/usr/lib/gcc/x86_64-linux-gnu/4.7/../../../x86_64-linux-gnu/libcheck.a(check.o): In function`tcase_create':
(.text+0x1a0): undefined reference to `floor'
/usr/lib/gcc/x86_64-linux-gnu/4.7/../../../x86_64-linux-gnu/libcheck.a(check.o): In function`tcase_set_timeout':
(.text+0x3f5): undefined reference to `floor'
/usr/lib/gcc/x86_64-linux-gnu/4.7/../../../x86_64-linux-gnu/libcheck.a(check.o): In function`tcase_set_timeout':
(.text+0x409): undefined reference to `floor'
/usr/lib/gcc/x86_64-linux-gnu/4.7/../../../x86_64-linux-gnu/libcheck.a(check_pack.o): In function`ppack':
(.text+0x51d): undefined reference to `__pthread_register_cancel'
/usr/lib/gcc/x86_64-linux-gnu/4.7/../../../x86_64-linux-gnu/libcheck.a(check_pack.o): In function`ppack':
(.text+0x551): undefined reference to `__pthread_unregister_cancel'
/usr/lib/gcc/x86_64-linux-gnu/4.7/../../../x86_64-linux-gnu/libcheck.a(check_run.o): In function`srunner_run':
(.text+0x965): undefined reference to `timer_create'
/usr/lib/gcc/x86_64-linux-gnu/4.7/../../../x86_64-linux-gnu/libcheck.a(check_run.o): In function`srunner_run':
(.text+0x9b3): undefined reference to `timer_settime'
/usr/lib/gcc/x86_64-linux-gnu/4.7/../../../x86_64-linux-gnu/libcheck.a(check_run.o): In function`srunner_run':
(.text+0x9d9): undefined reference to `timer_delete'
collect2: error: ld returned 1 exit status
make[2]: *** [auto_tests/messenger_test] Error 1
make[1]: *** [auto_tests/CMakeFiles/messenger_test.dir/all] Error 2
make: *** [all] Error 2
`
Everything else compiles fine.
